"""empty message

Revision ID: 233665712fd5
Revises: None
Create Date: 2015-12-19 19:59:34.103484

"""

# revision identifiers, used by Alembic.
revision = '233665712fd5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temprature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m1', sa.String(length=100), nullable=True),
    sa.Column('m2', sa.String(length=100), nullable=True),
    sa.Column('m3', sa.String(length=100), nullable=True),
    sa.Column('m4', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temprature')
    ### end Alembic commands ###
