"""empty message

Revision ID: 2eec1c74485a
Revises: None
Create Date: 2015-12-19 15:58:25.610033

"""

# revision identifiers, used by Alembic.
revision = '2eec1c74485a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temprature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m1', sa.String(), nullable=True),
    sa.Column('m2', sa.String(), nullable=True),
    sa.Column('m3', sa.String(), nullable=True),
    sa.Column('m4', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test3')
    op.drop_table('test2')
    op.drop_table('test1')
    op.drop_table('temprature')
    ### end Alembic commands ###
