"""empty message

Revision ID: dad2b63676d4
Revises: 2eec1c74485a
Create Date: 2015-12-19 16:27:34.034196

"""

# revision identifiers, used by Alembic.
revision = 'dad2b63676d4'
down_revision = '2eec1c74485a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test1')
    op.drop_table('test2')
    op.drop_table('test3')
    op.add_column('temprature', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temprature', 'timestamp')
    op.create_table('test3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
